//eslint-disable-next-line
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  '17TRACK quota notification': {
    en: 'Telegram warning when fewer than 20 17TRACK shipments remain',
    de: 'Telegram-Warnung bei weniger als 20 verbleibenden 17TRACK-Sendungen',
    ru: 'Предупреждение Telegram при остатке менее 20 отправлений 17TRACK',
    pt: 'Aviso no Telegram quando restarem menos de 20 envios 17TRACK',
    nl: 'Telegramwaarschuwing bij minder dan 20 resterende 17TRACK-zendingen',
    fr: 'Alerte Telegram lorsque le quota 17TRACK est inférieur à 20 envois',
    it: 'Avviso Telegram con meno di 20 spedizioni 17TRACK disponibili',
    es: 'Aviso por Telegram cuando queden menos de 20 envíos 17TRACK',
    pl: 'Ostrzeżenie Telegram przy mniej niż 20 pozostałych przesyłkach 17TRACK',
    uk: 'Попередження Telegram, коли залишилося менш ніж 20 відправлень 17TRACK',
    'zh-cn': '17TRACK剩余运单额度少于20时发送Telegram提醒',
  },
  'parcel adapter settings': {
    en: 'Adapter settings for parcel',
    de: 'Adaptereinstellungen für parcel',
    ru: 'Настройки адаптера для parcel',
    pt: 'Configurações do adaptador para parcel',
    nl: 'Adapterinstellingen voor parcel',
    fr: "Paramètres d'adaptateur pour parcel",
    it: "Impostazioni dell'adattatore per parcel",
    es: 'Ajustes del adaptador para parcel',
    pl: 'Ustawienia adaptera dla parcel',
    'zh-cn': 'parcel的适配器设置',
  },
  'App Email': {
    en: 'App Email',
    de: 'App-E-Mail',
    ru: 'Электронная почта приложения',
    pt: 'Email do aplicativo',
    nl: 'App-e-mail',
    fr: "Courriel de l'application",
    it: "E-mail dell'app",
    es: 'Correo electrónico de la aplicación',
    pl: 'E-mail aplikacji',
    'zh-cn': '应用电子邮件',
  },
  'App Password': {
    en: 'App Password',
    de: 'App-Passwort',
    ru: 'Пароль приложения',
    pt: 'Senha de app',
    nl: 'App-wachtwoord',
    fr: "Mot de passe de l'application",
    it: "Password dell'app",
    es: 'Contraseña de la aplicación',
    pl: 'Hasło do aplikacji',
    'zh-cn': '应用密码',
  },
  'Update interval (in minutes)': {
    en: 'Update interval (in minutes)',
    de: 'Aktualisierungsintervall (in Minuten)',
    ru: 'Интервал обновления (в минутах)',
    pt: 'Intervalo de atualização (em minutos)',
    nl: 'Update-interval (in minuten)',
    fr: 'Intervalle de mise à jour (en minutes)',
    it: 'Intervallo di aggiornamento (in minuti)',
    es: 'Intervalo de actualización (en minutos)',
    pl: 'Interwał aktualizacji (w minutach)',
    'zh-cn': '更新间隔（分钟）',
  },
};
